language: scala
sudo: required
dist: trusty
addons:
  apt:
    update: true

before_script:
  - git fetch --tags
jdk:
  - oraclejdk8

matrix:
  include:
    - scala: 2.13.3
      script: sbt ++$TRAVIS_SCALA_VERSION! utestJVM/test utestJS/test

before_cache:
  - rm -f $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.sbt -name "*.lock" -type f -delete
cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt
